### ISSUE TITLE
Change from sqlalchemy to oreader 

### ISSUE THREAD

**Issue by jcrudy** [mattlewissf/mimic#1]
This change will be almost entirely in [mapper.py](https://github.com/mattlewissf/mimic/blob/master/mimic_package/data_model/mapper.py).  You can find [oreader here](https://github.com/jcrudy/oreader).  I would suggest looking at this [test file](https://github.com/jcrudy/oreader/blob/master/oreader/test/test_readers_and_writers.py) to get started with oreader.  In particular, look at the `test_read_write` function.  It shows a basic example.

**Comment by mattlewissf** [comment]
@RobertShultz (who I know is in NZ) - I'm gonna take a stab at this before you get back

**Comment by RobertShultz** [comment]
Hey Matt,

My bad, I meant to email you about my trip before I left. Jason mentioned
that you would probably tackle this task if you had the time.

I have some questions for you about creating the database and other basic
stuff. I will be back in the states on the 16th.

Thanks,
Bobby

**Comment by mattlewissf** [comment]
No worries!

**Comment by mattlewissf** [comment]
@jcrudy: while working on re-writing this in Oreader-ese, a few questions:  

- for setting up 'identity_key' tuples - is this all of the PK and FK's that were mapped? 
- what is the purpose of container_key? Does this always just map to the identity_key setup? 
- when setting up the schema through the @schema decorator, does this also just apply to PR/FKs, or should I be setting up all fields there? Previously this had been done in standard.py but not in mapper.py

**Comment by jcrudy** [comment]
@mattlewissf 

1. The identity key is usually going to be a primary key of some kind, but not necessarily the same primary key used in the database.  It must uniquely identify an individual object of the type.  If there are relationships in which the type is a parent, the identity key will also be used as a foreign key by the child types.  You might have to examine the schema to see what columns make sense to use for this.

2. The container key is basically a foreign key.  It should match the identity key of the parent.

3. You have to map all columns, but you should do this with the `sqa_schema` decorator since you already have sqlalchemy `Table` objects from the metadata object.

**Comment by mattlewissf** [comment]
Done
